apiVersion: v1
kind: Pod
metadata:
  name: testpod3
  labels:
    env: test
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1
spec:
  containers:
  - name: appcntr3 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        cpu: "1"
        memory: "512Mi"
        intel.com/sriov: '1' 
      limits:
        cpu: "1"
        memory: "512Mi"
        intel.com/sriov: '1'
