# Tested with golangci-lint ver. 2.x
version: "2"

run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - asciicheck        # checks for non-ASCII identifiers
    - bidichk           # checks for dangerous unicode sequences (security)
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errname           # checks error naming conventions
    - exhaustive
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives  # validates go compiler directives
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero          # finds slice declarations with non-zero initial length
    - misspell
    - mnd
    - nakedret
    - prealloc
    - reassign          # checks package variable reassignment
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: "logging is allowed only by logutils.Log"
    dupl:
      threshold: 100
    funlen:
      statements: 50
      lines: 100
    lll:
      line-length: 140
    mnd:
      # don't include the "operation" and "assign"
      checks: ["argument", "case", "condition", "return"]
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G304
    ginkgolinter:
      forbid-focus-container: true
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -QF1001
        - -QF1003
        - -QF1008
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
        - github.com/onsi/gomega/gstruct

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - .github/*
      - deployments/*
      - docs/*
      - pkg/utils/testing.go
      - pkg/resources/testing.go
    rules:
      - linters:
          - dupl
          - goconst
          - lll
          - gosec
        path: _test\.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/k8snetworkplumbingwg/sriov-network-device-plugin)
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/k8snetworkplumbingwg/sriov-network-device-plugin
