// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import ghw "github.com/jaypipes/ghw"
import mock "github.com/stretchr/testify/mock"
import types "github.com/intel/sriov-network-device-plugin/pkg/types"

// DeviceProvider is an autogenerated mock type for the DeviceProvider type
type DeviceProvider struct {
	mock.Mock
}

// AddTargetDevices provides a mock function with given fields: _a0, _a1
func (_m *DeviceProvider) AddTargetDevices(_a0 []*ghw.PCIDevice, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func([]*ghw.PCIDevice, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDevices provides a mock function with given fields:
func (_m *DeviceProvider) GetDevices() []types.PciDevice {
	ret := _m.Called()

	var r0 []types.PciDevice
	if rf, ok := ret.Get(0).(func() []types.PciDevice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.PciDevice)
		}
	}

	return r0
}
