// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/intel/sriov-network-device-plugin/pkg/types"

// DeviceFilter is an autogenerated mock type for the DeviceFilter type
type DeviceFilter struct {
	mock.Mock
}

// GetFilteredDevices provides a mock function with given fields: _a0
func (_m *DeviceFilter) GetFilteredDevices(_a0 []types.PciDevice) []types.PciDevice {
	ret := _m.Called(_a0)

	var r0 []types.PciDevice
	if rf, ok := ret.Get(0).(func([]types.PciDevice) []types.PciDevice); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.PciDevice)
		}
	}

	return r0
}
