// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LinkWatcher is an autogenerated mock type for the LinkWatcher type
type LinkWatcher struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields:
func (_m *LinkWatcher) Subscribe() {
	_m.Called()
}
