// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LinkWatcher is an autogenerated mock type for the LinkWatcher type
type LinkWatcher struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields:
func (_m *LinkWatcher) Subscribe() {
	_m.Called()
}

type mockConstructorTestingTNewLinkWatcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewLinkWatcher creates a new instance of LinkWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLinkWatcher(t mockConstructorTestingTNewLinkWatcher) *LinkWatcher {
	mock := &LinkWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
