// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	types "github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockDeviceSelector is an autogenerated mock type for the DeviceSelector type
type MockDeviceSelector struct {
	mock.Mock
}

// Filter provides a mock function with given fields: _a0
func (_m *MockDeviceSelector) Filter(_a0 []types.HostDevice) []types.HostDevice {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []types.HostDevice
	if rf, ok := ret.Get(0).(func([]types.HostDevice) []types.HostDevice); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.HostDevice)
		}
	}

	return r0
}

// NewMockDeviceSelector creates a new instance of MockDeviceSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceSelector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceSelector {
	mock := &MockDeviceSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
