// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockLinkWatcher is an autogenerated mock type for the LinkWatcher type
type MockLinkWatcher struct {
	mock.Mock
}

// Subscribe provides a mock function with no fields
func (_m *MockLinkWatcher) Subscribe() {
	_m.Called()
}

// NewMockLinkWatcher creates a new instance of MockLinkWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkWatcher {
	mock := &MockLinkWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
