// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	types "github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockVdpaDevice is an autogenerated mock type for the VdpaDevice type
type MockVdpaDevice struct {
	mock.Mock
}

// GetParent provides a mock function with no fields
func (_m *MockVdpaDevice) GetParent() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParent")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPath provides a mock function with no fields
func (_m *MockVdpaDevice) GetPath() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetType provides a mock function with no fields
func (_m *MockVdpaDevice) GetType() types.VdpaType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 types.VdpaType
	if rf, ok := ret.Get(0).(func() types.VdpaType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.VdpaType)
	}

	return r0
}

// NewMockVdpaDevice creates a new instance of MockVdpaDevice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVdpaDevice(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVdpaDevice {
	mock := &MockVdpaDevice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
