// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	kvdpa "github.com/k8snetworkplumbingwg/govdpa/pkg/kvdpa"
	mock "github.com/stretchr/testify/mock"
)

// VdpaProvider is an autogenerated mock type for the VdpaProvider type
type VdpaProvider struct {
	mock.Mock
}

// GetVdpaDeviceByPci provides a mock function with given fields: pciAddr
func (_m *VdpaProvider) GetVdpaDeviceByPci(pciAddr string) (kvdpa.VdpaDevice, error) {
	ret := _m.Called(pciAddr)

	var r0 kvdpa.VdpaDevice
	if rf, ok := ret.Get(0).(func(string) kvdpa.VdpaDevice); ok {
		r0 = rf(pciAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kvdpa.VdpaDevice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pciAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewVdpaProviderT interface {
	mock.TestingT
	Cleanup(func())
}

// NewVdpaProvider creates a new instance of VdpaProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVdpaProvider(t NewVdpaProviderT) *VdpaProvider {
	mock := &VdpaProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
