apiVersion: v1
kind: Pod
metadata:
  name: testpod-gtp
  labels:
    env: test
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net-gtp
spec:
  containers:
  - name: gtpcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/x700_gtp: 1
      limits:
        intel.com/x700_gtp: 1
# Note: requests / limits can be added automaticaly using
# network resources injector mutating webhook.
